destination:
  MPC_Paris:
    job:
      DOGMAN:
        dir_path: /mnt/mpcparis/DOGMAN/io/to_client/packages
        title: MPC PARIS PACKAGE FOR DOGMAN.
      Greek_Salad:
        dir_path: /mnt/mpcparis/Greek_Salad/io/to_client/packages
        title: MPC PARIS PACKAGE FOR Greek_Salad.
      NOTRE_DAME:
        dir_path: /mnt/mpcparis/NOTRE_DAME/io/To_Client/packages
        title: MPC PARIS PACKAGE FOR NOTRE_DAME.
      asterix:
        dir_path: /mnt/mpcparis/A5/io/To_Client/packages
        title: MPC PARIS PACKAGE FOR A5.
      test:
        dir_path: /mnt/mpcparis/tesr/io/To_Client/packages
        title: MPC PARIS PACKAGE FOR NOTRE_DAME.
    pkg_version_padding: 4
    pkg_version_prefix: v
    vendor: dasein
  filmgate:
    job:
      KILL:
        dir_path: /mnt/pb6/Filmgate/KILL/io/To_Client/Package
        title: FILMGATE PACKAGE FOR KILL.
      TRM:
        dir_path: /mnt/pb6/Filmgate/TRM/io/To_Client/Package
        title: FILMGATE PACKAGE FOR TRM.
    pkg_version_padding: 4
    pkg_version_prefix: v
    vendor: dasein
