destination:
  MPC_Paris:
    job:
      DOGMAN:
        dir_path: /mnt/mpcparis/DOGMAN/io/to_client/packages
        title: MPC PARIS PACKAGE FOR DOGMAN.
      ECODLAIR:
        dir_path: /mnt/mpcparis/ECODLAIR/io/to_client/packages
        title: MPC PARIS PACKAGE FOR ECODLAIR.
      Greek_Salad:
        dir_path: /mnt/mpcparis/Greek_Salad/io/to_client/packages
        title: MPC PARIS PACKAGE FOR Greek_Salad.
      LABETE:
        dir_path: /mnt/mpcparis/LABETE/io/to_client/packages
        title: MPC PARIS PACKAGE FOR LABETE.
      LATRESSE:
        dir_path: /mnt/mpcparis/LATRESSE/io/to_client/packages
        title: MPC PARIS PACKAGE FOR LATRESSE.
      LRDO:
        dir_path: /mnt/mpcparis/LRDO/io/to_client/packages
        title: MPC PARIS PACKAGE FOR LRDO.
      MARINET:
        dir_path: /mnt/mpcparis/MARINET/io//to_client/packages
        title: MPC PARIS PACKAGE FOR MARINET.
      NOTRE_DAME:
        dir_path: /mnt/mpcparis/NOTRE_DAME/io/to_client/packages
        title: MPC PARIS PACKAGE FOR NOTRE_DAME.
      PAF:
        dir_path: /mnt/mpcparis/PAF/io//to_client/packages
        title: MPC PARIS PACKAGE FOR PAF.
      WONDERMAN:
        dir_path: /mnt/mpcparis/WONDERMAN/io//to_client/packages
        title: MPC PARIS PACKAGE FOR WONDERMAN.
      asterix:
        dir_path: /mnt/mpcparis/A5/io/to_client/packages
        title: MPC PARIS PACKAGE FOR A5.
      test:
        dir_path: /mnt/mpcparis/tesr/io/to_client/packages
        title: MPC PARIS PACKAGE FOR NOTRE_DAME.
    pkg_version_padding: 4
    pkg_version_prefix: v
    vendor: dasein
  filmgate:
    job:
      Boderland:
        dir_path: /mnt/pb6/Filmgate/Boderland/io/To_Client/Package
        title: FILMGATE PACKAGE FOR Boderland.
      KILL:
        dir_path: /mnt/pb6/Filmgate/KILL/io/To_Client/Package
        title: FILMGATE PACKAGE FOR KILL.
      TRM:
        dir_path: /mnt/pb6/Filmgate/TRM/io/To_Client/Package
        title: FILMGATE PACKAGE FOR TRM.
    pkg_version_padding: 4
    pkg_version_prefix: v
    vendor: dasein
