destination:
  MPC_Paris:
    job:
      NOTRE_DAME:
        dir_path: /mnt/mpcparis/NOTRE_DAME/io/To_Client/packages
        title: MPC PARIS PACKAGE FOR NOTRE_DAME.
      asterix:
        dir_path: /mnt/mpcparis/A5/io/To_Client/packages
        title: MPC PARIS PACKAGE FOR A5.
      test:
        dir_path: /mnt/mpcparis/tesr/io/To_Client/packages
        title: MPC PARIS PACKAGE FOR NOTRE_DAME.
    pkg_version_padding: 4
    pkg_version_prefix: v
    vendor: dasein
  filmgate:
    job:
      TRM:
        dir_path: /mnt/pb6/Filmgate/TRM/io/To_Client/Package
        title: FILMGATE PACKAGE FOR TRM.
    pkg_version_padding: 4
    pkg_version_prefix: v
    vendor: dasein
